---
title: "Summary of WES dataset"
author: "Mafe Senosain"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(maftools)
library(dplyr)
library(knitr)
maf_dir <- "~/Library/Mobile Documents/com~apple~CloudDocs/Documents/Vanderbilt/Massion_Lab/Projects/CyTOF_ADC_project/Data/WES/TwistWES_Tumor_pipeline.filter.allSamples.maf"
clin_dt <- read.csv(file = '/Users/senosam/Documents/Massion_lab/CyTOF_summary/CDE_TMA36_2021JAN13_SA_MF.csv')
```

# Pre-processing of the data
```{r}
single.maf.delim <- read.delim(file = maf_dir, sep = "\t", header = TRUE, fill = TRUE, comment.char = "#")
laml <- read.maf(maf=single.maf.delim) ###optional, add clinical annotation file with "clinicalData" argument in read.maf()

x = getClinicalData(laml)
x$Tumor_Sample_Barcode = as.character(x$Tumor_Sample_Barcode)
pt_ID <- sapply(strsplit(x$Tumor_Sample_Barcode, "pt"), "[[", 2)
pt_ID <- sapply(strsplit(pt_ID, "_"), "[[", 1)

clin_dt <- clin_dt[match(pt_ID, clin_dt$pt_ID),]
clin_dt <- cbind('Tumor_Sample_Barcode'=x$Tumor_Sample_Barcode, clin_dt)
laml = read.maf(maf = single.maf.delim, clinicalData = clin_dt, verbose = F)
```

# MAF object
```{r}
laml
```

```{r}
plotmafSummary(maf = laml, rmOutlier = TRUE, addStat = 'median', dashboard = TRUE, titvRaw = FALSE)
```

# Oncoplots
```{r}
oncoplot(maf = laml, top = 25, clinicalFeatures = c('n_op1', 'n_op2'))
```

# Transition and Transversions
```{r}
laml.titv = titv(maf = laml, plot = FALSE, useSyn = TRUE)
#plot titv summary
plotTiTv(res = laml.titv)
```

# KRAS mutations
```{r}
lollipopPlot(maf = laml, gene = 'KRAS', AACol = 'Protein_Change', showMutationRate = TRUE)
lollipopPlot(maf = laml, gene = 'KRAS', showDomainLabel = FALSE, labelPos = 'all')
```

# Compare mutation load against TCGA cohorts
```{r}
laml.mutload = tcgaCompare(maf = laml, cohortName = 'TMA36', )
```

# Somatic Interactions
```{r}
somaticInteractions(maf = laml, top = 25, pvalue = c(0.05, 0.1))
```

# Detecting cancer driver genes based on positional clustering

```{r}
laml.sig = oncodrive(maf = laml, AACol = 'Protein_Change', minMut = 5, pvalMethod = 'zscore')
```

```{r}
kable(head(laml.sig))
#head(laml.sig)
plotOncodrive(res = laml.sig, fdrCutOff = 0.2, useFraction = TRUE)
```

# Clinical enrichment analysis
```{r}
histology = clinicalEnrichment(maf = laml, clinicalFeature = 'Hist_predominant')
stage = clinicalEnrichment(maf = laml, clinicalFeature = 'X8th_ed_path_stage')
n_op1 = clinicalEnrichment(maf = laml, clinicalFeature = 'n_op1')
n_op2 = clinicalEnrichment(maf = laml, clinicalFeature = 'n_op2')
```

```{r}
histology$groupwise_comparision[p_value < 0.05]
plotEnrichmentResults(enrich_res = histology, pVal = 0.05)
plotEnrichmentResults(enrich_res = stage, pVal = 0.05)
plotEnrichmentResults(enrich_res = n_op1, pVal = 0.05)
plotEnrichmentResults(enrich_res = n_op2, pVal = 0.05)
```

# Oncogenic Signaling Pathways
```{r}
OncogenicPathways(maf = laml)
PlotOncogenicPathways(maf = laml, pathways = "RTK-RAS")
```

```{r}
mut_dt <- read.csv(file='/Users/senosam/Documents/Massion_lab/WES_summary/summary/binaryWES.csv', row.names = 1)
pt_ID <- sapply(strsplit(clin_dt$Tumor_Sample_Barcode, "pt"), "[[", 2)
pt_ID <- sapply(strsplit(pt_ID, "_"), "[[", 1)
mut_dt <- mut_dt[match(pt_ID, rownames(mut_dt)),]
mut_dt['n_op1'] <- clin_dt$n_op1
mut_dt['n_op2'] <- clin_dt$n_op2
```

```{r}
#c('KRAS','EGFR','STK11', 'ALK', 'TP53')
```
